mode = "local"
project = ""
shell = ""

[dirs]
project = []
python = "isolated"
data = "/home/foreverzzz/.local/share/hatch"
cache = "/home/foreverzzz/.cache/hatch"

[dirs.env]

[projects]

[publish.index]
repo = "main"

[template]
name = "4everzzz"
email = "shurikshovyrin1@gmail.com"

[template.licenses]
headers = true
default = [
    "MIT",
]

[template.plugins.default]
tests = true
ci = false
src-layout = true

[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
